project:
  type: website
  output-dir: docs
  
website:
  title: "florianbuetow.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



